#!/usr/bin/env bash
#Script to install Python, create a virtual environment and install dependencies

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" || exit 3

if ! command -v python3 >/dev/null 2>&1; then
  sudo ./pacapt install python3 python3-pip python3-venv
fi

cd ../backend

if [ ! -d .venv ]; then
  echo Creating virtual enviroment \(.venv\)
  python3 -m venv .venv
fi

source ./.venv/bin/activate

pip install -r requirements.txt

deactivate
cd ..


echo Installation completed